/*
 * Auto-generated by ida_auto_nvram.py at 2026-05-28 18:58:13.
 *
 * Build examples:
 *   mipsel-linux-uclibc-gcc -shared -fPIC -O2 -o libnvram.so.0 nvram_fake.c
 *   arm-linux-gnueabi-gcc    -shared -fPIC -O2 -o libnvram.so.0 nvram_fake.c
 *   gcc                      -shared -fPIC -O2 -o libnvram.so.0 nvram_fake.c
 *
 * Runtime:
 *   export NVRAM_FAKE_INI=/path/to/nvram.ini
 *   LD_PRELOAD=./libnvram.so.0 ./goahead
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdint.h>
#include <ctype.h>

#ifndef NVRAM_FAKE_GETALL_MAX
#define NVRAM_FAKE_GETALL_MAX 32768
#endif

typedef struct {
    const char *key;
    const char *value;
    const char *source;
} nvram_kv_t;

static nvram_kv_t static_kv[] = {
    { "20AP_unknown", "", "heuristic" },
    { "__assert", "", "heuristic" },
    { "__bss_start", "", "heuristic" },
    { "__ctype_b", "", "heuristic" },
    { "__ctype_tolower", "", "heuristic" },
    { "__ctype_toupper", "", "heuristic" },
    { "__deregister_frame_info", "", "heuristic" },
    { "__errno_location", "", "heuristic" },
    { "__fgetc_unlocked", "", "heuristic" },
    { "__floatdisf", "", "heuristic" },
    { "__register_frame_info", "", "heuristic" },
    { "__RLD_MAP", "", "heuristic" },
    { "__uClibc_main", "", "heuristic" },
    { "__UNDEF__", "", "heuristic" },
    { "_DYNAMIC_LINKING", "", "heuristic" },
    { "_edata", "", "heuristic" },
    { "_end", "", "heuristic" },
    { "_fbss", "", "heuristic" },
    { "_fdata", "", "heuristic" },
    { "_fini", "", "heuristic" },
    { "_ftext", "", "heuristic" },
    { "_GLOBAL_OFFSET_TABLE_", "", "heuristic" },
    { "_gp", "", "heuristic" },
    { "_Jv_RegisterClasses", "", "heuristic" },
    { "_unknown", "", "heuristic" },
    { "abg_rate", "", "heuristic" },
    { "ABOVE", "HT_EXTCHA", "api-set-arg0" },
    { "AccessControlList", "", "heuristic" },
    { "AccessControlList0", "actrlFlag", "api-set-arg1" },
    { "AccessControlList1", "", "heuristic" },
    { "AccessControlList2", "", "heuristic" },
    { "AccessControlList3", "", "heuristic" },
    { "AccessPolicy", "", "heuristic" },
    { "AccessPolicy0", "", "heuristic" },
    { "AccessPolicy1", "", "heuristic" },
    { "AccessPolicy2", "", "heuristic" },
    { "AccessPolicy3", "", "heuristic" },
    { "AckPolicy", "", "heuristic" },
    { "acl_rules", "", "heuristic" },
    { "aclindex", "", "heuristic" },
    { "actrlFlag", "actrlFlag", "api-set-arg1" },
    { "admuser", "admin", "forced-policy" },
    { "advEnableWPS", "0", "heuristic" },
    { "af_index", "", "heuristic" },
    { "ALG_FTP", "1", "api-set-arg1" },
    { "alg_ftp_enable", "0", "heuristic" },
    { "ALG_IPSEC", "1", "api-set-arg1" },
    { "alg_ipsec_enable", "0", "heuristic" },
    { "ALG_L2TP", "1", "api-set-arg1" },
    { "alg_l2tp_enable", "0", "heuristic" },
    { "alg_passthrough", "", "heuristic" },
    { "ALG_PPTP", "1", "api-set-arg1" },
    { "alg_pptp_enable", "0", "heuristic" },
    { "ALG_SIP", "0", "api-set-arg1" },
    { "alg_sip_enable", "0", "heuristic" },
    { "AllowIp", "192.168.10.200", "heuristic" },
    { "AllowPort", "", "heuristic" },
    { "AntiDoSEnable", "0", "api-set-arg1" },
    { "ap_ackpolicy_all", "", "heuristic" },
    { "ap_acm_all", "", "heuristic" },
    { "ap_aifsn_all", "", "heuristic" },
    { "ap_cwmax_all", "", "heuristic" },
    { "ap_cwmin_all", "", "heuristic" },
    { "ap_txop_all", "", "heuristic" },
    { "APACM", "", "heuristic" },
    { "APAifsn", "", "heuristic" },
    { "apcli_bssid", "00:11:22:33:44:55", "heuristic" },
    { "apcli_bssid_5g", "00:11:22:33:44:55", "heuristic" },
    { "apcli_channel", "0", "api-set-arg1" },
    { "apcli_channel_5g", "", "heuristic" },
    { "apcli_chwidth_5g", "", "heuristic" },
    { "apcli_default_key", "", "heuristic" },
    { "apcli_default_key_5g", "", "heuristic" },
    { "apcli_enc", "", "heuristic" },
    { "apcli_enc_5g", "", "heuristic" },
    { "apcli_extchannel", "", "heuristic" },
    { "apcli_extchannel_5g", "", "heuristic" },
    { "apcli_key1", "", "heuristic" },
    { "apcli_key1_5g", "", "heuristic" },
    { "apcli_key1type", "", "heuristic" },
    { "apcli_key1type_5g", "", "heuristic" },
    { "apcli_key2", "", "heuristic" },
    { "apcli_key2_5g", "", "heuristic" },
    { "apcli_key2type", "", "heuristic" },
    { "apcli_key2type_5g", "", "heuristic" },
    { "apcli_key3", "", "heuristic" },
    { "apcli_key3_5g", "", "heuristic" },
    { "apcli_key3type", "", "heuristic" },
    { "apcli_key3type_5g", "", "heuristic" },
    { "apcli_key4", "", "heuristic" },
    { "apcli_key4_5g", "", "heuristic" },
    { "apcli_key4type", "", "heuristic" },
    { "apcli_key4type_5g", "", "heuristic" },
    { "apcli_mode", "0", "heuristic" },
    { "apcli_mode_5g", "0", "heuristic" },
    { "apcli_scan_count", "0", "heuristic" },
    { "apcli_ssid", "test", "heuristic" },
    { "apcli_ssid_5g", "test", "heuristic" },
    { "apcli_wireless_mode_5g", "0", "heuristic" },
    { "apcli_wpapsk", "admin", "heuristic" },
    { "apcli_wpapsk_5g", "admin", "heuristic" },
    { "ApCliAuthMode", "9", "api-set-arg1" },
    { "ApCliBssid", "00:11:22:33:44:55", "heuristic" },
    { "ApCliDefaultKeyID", "", "heuristic" },
    { "ApCliEnable", "1", "api-set-arg1" },
    { "ApCliEncrypType", "", "heuristic" },
    { "apClient", "0", "api-set-arg1" },
    { "ApCliKey1Type", "8", "api-set-arg1" },
    { "ApCliKey2Type", "1", "api-set-arg1" },
    { "ApCliKey3Type", "1", "api-set-arg1" },
    { "ApCliKey4Type", "", "heuristic" },
    { "ApcliScan_5g", "", "heuristic" },
    { "ApCliSsid1", "test", "heuristic" },
    { "ApCliWPAPSK", "admin", "heuristic" },
    { "APCwmax", "", "heuristic" },
    { "APCwmin", "", "heuristic" },
    { "apsd_capable", "", "heuristic" },
    { "APSDCapable", "", "heuristic" },
    { "APTxop", "", "heuristic" },
    { "ASCertFile", "", "heuristic" },
    { "AUTH_TYPE", "", "heuristic" },
    { "authM", "=%s\\n", "string-kv" },
    { "AuthMode", "WPAPSKWPA2PSK", "api-set-arg1" },
    { "authserver", "", "heuristic" },
    { "authType", "", "heuristic" },
    { "AutoChannelSelect", "2", "api-set-arg1" },
    { "basic_rate", "", "heuristic" },
    { "BasicRate", "351", "api-set-arg1" },
    { "BeaconPeriod", "", "heuristic" },
    { "bg_protection", "", "heuristic" },
    { "BGProtection", "", "heuristic" },
    { "BlockPortScan", "0", "api-set-arg1" },
    { "blockPortScanEnabled", "0", "heuristic" },
    { "BlockSynFlood", "0", "api-set-arg1" },
    { "blockSynFloodEnabled", "0", "heuristic" },
    { "boot_init_ip_port_filter", "", "heuristic" },
    { "broadcastssid", "test", "heuristic" },
    { "BSSACM", "", "heuristic" },
    { "BSSAifsn", "", "heuristic" },
    { "BSSCwmax", "", "heuristic" },
    { "BSSCwmin", "", "heuristic" },
    { "BssidNum", "1", "heuristic" },
    { "BSSTxop", "", "heuristic" },
    { "carrier_detect", "", "heuristic" },
    { "CarrierDetect", "", "heuristic" },
    { "CCK", "", "heuristic" },
    { "cert", "", "heuristic" },
    { "Channel", "HT", "api-set-arg1" },
    { "channel", "", "heuristic" },
    { "CliMode", "0", "api-set-arg1" },
    { "climode", "0", "heuristic" },
    { "confirmlogin", "admin", "forced-policy" },
    { "connectionType", "", "heuristic" },
    { "CONTENT_LENGTH", "", "heuristic" },
    { "CONTENT_TYPE", "", "heuristic" },
    { "country_code", "0", "heuristic" },
    { "CountryCode", "0", "heuristic" },
    { "CountryRegion", "5", "api-set-arg1" },
    { "CountryRegionABand", "0", "api-set-arg1" },
    { "custom_interface", "", "heuristic" },
    { "d_getautobootHtm", "", "heuristic" },
    { "d_getCurrentTimeASP", "", "heuristic" },
    { "d_getDhcpCliList", "", "heuristic" },
    { "d_getPCMac", "00:11:22:33:44:55", "heuristic" },
    { "DDNS", "8.8.8.8", "heuristic" },
    { "ddns.sh", "8.8.8.8", "heuristic" },
    { "DDNSAccount", "8.8.8.8", "heuristic" },
    { "DDNSEnable", "8.8.8.8", "heuristic" },
    { "DDNSPassword", "admin", "forced-policy" },
    { "ddnsProv", "8.8.8.8", "heuristic" },
    { "DDNSProvider", "8.8.8.8", "heuristic" },
    { "ddos_en", "", "heuristic" },
    { "default_download_queue_ceil", "", "heuristic" },
    { "default_download_queue_rate", "", "heuristic" },
    { "default_upload_queue_ceil", "", "heuristic" },
    { "default_upload_queue_rate", "", "heuristic" },
    { "DefaultFirewallPolicy", "0", "api-set-arg1" },
    { "DefaultKeyID", "", "heuristic" },
    { "delete_rule", "", "heuristic" },
    { "DHCP", "", "heuristic" },
    { "dhcpc_hostname", "", "heuristic" },
    { "dhcpc_mtusize", "1500", "heuristic" },
    { "dhcpEnabled", "0", "api-set-arg1" },
    { "dhcpEnabled_tmp", "0", "heuristic" },
    { "dhcpEnd", "", "heuristic" },
    { "dhcpGateway", "192.168.0.1", "api-set-arg1" },
    { "dhcpLease", "", "heuristic" },
    { "dhcpMask", "255.0.0.0", "api-set-arg1" },
    { "DHCPPLUS", "", "heuristic" },
    { "dhcpplus_server", "", "heuristic" },
    { "dhcppluspass", "admin", "heuristic" },
    { "dhcpplususer", "admin", "forced-policy" },
    { "dhcpPriDns", "1", "api-set-arg1" },
    { "dhcpRangeEnd", "", "heuristic" },
    { "dhcpRangeStart", "", "heuristic" },
    { "dhcpSecDns", "192.168.0.1", "api-set-arg1" },
    { "dhcpserver", "", "heuristic" },
    { "dhcpStart", "255.255.255.0", "api-set-arg1" },
    { "dhcpStatic1", "", "heuristic" },
    { "dhcpStatic2", "", "heuristic" },
    { "dhcpStatic3", "", "heuristic" },
    { "DhcpStaticRulesStr", "invalid DHCP End IP", "api-set-arg1" },
    { "dip_address", "", "heuristic" },
    { "dip_address2", "", "heuristic" },
    { "dir_setWanWifi", "", "heuristic" },
    { "dir_wizard_setup", "", "heuristic" },
    { "dls_capable", "", "heuristic" },
    { "DLSCapable", "", "heuristic" },
    { "DMZ", "", "heuristic" },
    { "DMZAvoidTCPPort80", "", "heuristic" },
    { "DMZEnable", "0", "api-set-arg1" },
    { "DMZEnabled", "0", "heuristic" },
    { "DMZIPAddress", "192.168.10.200", "heuristic" },
    { "dns1", "8.8.8.8", "heuristic" },
    { "dns2", "8.8.8.8", "heuristic" },
    { "dns_ctrl", "8.8.8.8", "heuristic" },
    { "dns_relay", "8.8.8.8", "heuristic" },
    { "dnsmode", "8.8.8.8", "heuristic" },
    { "dnsPEnabled", "8.8.8.8", "heuristic" },
    { "dnspEnbl", "8.8.8.8", "heuristic" },
    { "dnsRelayEN", "8.8.8.8", "heuristic" },
    { "dnsserver", "8.8.8.8", "heuristic" },
    { "dnsserver2", "8.8.8.8", "heuristic" },
    { "download_file", "", "heuristic" },
    { "DownloadBandwidth_Custom", "", "heuristic" },
    { "dp_index", "", "heuristic" },
    { "drop_unmatched_pkts", "", "heuristic" },
    { "dstnetmask", "255.255.255.0", "heuristic" },
    { "DtimPeriod", "", "heuristic" },
    { "E_ASSERT", "", "heuristic" },
    { "E_LOG", "", "heuristic" },
    { "E_NULL", "", "heuristic" },
    { "E_USER", "admin", "forced-policy" },
    { "EAP_FAIL_RECEIVED", "", "heuristic" },
    { "EAP_INVALID_DATA", "", "heuristic" },
    { "EAP_NONCE_MISMATCH", "", "heuristic" },
    { "EAP_REQ_WRONG_SMI", "", "heuristic" },
    { "EAP_REQ_WRONG_VENDOR_TYPE", "", "heuristic" },
    { "EAPifname", "", "heuristic" },
    { "enable_all_select_filter_rules", "0", "heuristic" },
    { "enable_index_filter_rules", "0", "heuristic" },
    { "enable_ssid1", "test", "heuristic" },
    { "EnableAllRules", "0", "heuristic" },
    { "enableWhitelist", "0", "heuristic" },
    { "EncrypType", "actrlFlag", "api-set-arg1" },
    { "eth2.2", "macCloneMac", "api-set-arg0" },
    { "ETxBfEnCond", "", "heuristic" },
    { "ETxBfIncapable", "1", "api-set-arg1" },
    { "find_unused_index", "", "heuristic" },
    { "firewall.c", "", "heuristic" },
    { "FixedTxMode", "CCK", "api-set-arg1" },
    { "flag_5G", "", "heuristic" },
    { "flag_wizard", "1", "api-set-arg1" },
    { "flagMode", "0", "heuristic" },
    { "Force_mem_upgrade", "1", "api-set-arg1" },
    { "form_define_ip_control", "", "heuristic" },
    { "FragThreshold", "", "heuristic" },
    { "ftp_alg", "", "heuristic" },
    { "g_autobootHtm", "", "heuristic" },
    { "g_LanWanConflict", "", "heuristic" },
    { "g_Raix_wsc_configured", "", "heuristic" },
    { "g_Raix_WscResult", "", "heuristic" },
    { "g_wsc_configured", "", "heuristic" },
    { "gateway", "192.168.10.200", "heuristic" },
    { "GATEWAY_INTERFACE", "192.168.10.200", "heuristic" },
    { "get_index_port_forward_rule", "", "heuristic" },
    { "get_index_rule_define", "", "heuristic" },
    { "get_mac_ip_port_filter_basic_setting", "00:11:22:33:44:55", "heuristic" },
    { "get_system_info", "", "heuristic" },
    { "get_wsc_profile", "", "heuristic" },
    { "GetConnectStatus_5g", "", "heuristic" },
    { "GetConnectStatus_start", "", "heuristic" },
    { "GetConnectStatus_start_5g", "", "heuristic" },
    { "Hiddenssid", "test", "heuristic" },
    { "hiddenssid", "test", "heuristic" },
    { "hiddenSSID", "test", "heuristic" },
    { "HideSSID", "test", "heuristic" },
    { "high_download_queue_ceil", "", "heuristic" },
    { "high_download_queue_rate", "", "heuristic" },
    { "high_upload_queue_ceil", "", "heuristic" },
    { "high_upload_queue_rate", "", "heuristic" },
    { "highest_download_queue_ceil", "", "heuristic" },
    { "highest_download_queue_rate", "", "heuristic" },
    { "highest_upload_queue_ceil", "", "heuristic" },
    { "highest_upload_queue_rate", "", "heuristic" },
    { "HostName", "", "heuristic" },
    { "hour_end", "", "heuristic" },
    { "hour_start", "", "heuristic" },
    { "hssid", "test", "heuristic" },
    { "HT_AMSDU", "", "heuristic" },
    { "HT_AutoBA", "", "heuristic" },
    { "HT_BADecline", "", "heuristic" },
    { "HT_BSSCoexistence", "actrlFlag", "api-set-arg1" },
    { "HT_BW", "1", "api-set-arg1" },
    { "HT_DisallowTKIP", "192.168.10.200", "heuristic" },
    { "HT_EXTCHA", "0", "api-set-arg1" },
    { "HT_GI", "", "heuristic" },
    { "HT_MCS", "4", "api-set-arg1" },
    { "HT_OpMode", "0", "heuristic" },
    { "HT_RATE", "", "heuristic" },
    { "HT_RDG", "", "heuristic" },
    { "HT_RxStream", "", "heuristic" },
    { "HT_STBC", "", "heuristic" },
    { "HT_TxStream", "", "heuristic" },
    { "HTTP_AUTHORIZATION", "", "heuristic" },
    { "HTTP_HOST", "", "heuristic" },
    { "http_sharefile", "", "heuristic" },
    { "http_SharefileEnable", "0", "heuristic" },
    { "httpSharefileEnabled", "0", "heuristic" },
    { "hwnatEnabled", "1", "heuristic" },
    { "icmp_flood_en", "", "heuristic" },
    { "icmp_flood_enable", "0", "heuristic" },
    { "icmp_flood_threshold", "", "heuristic" },
    { "idle_timeout_interval", "0", "heuristic" },
    { "IEEE80211H", "", "heuristic" },
    { "IEEE8021X", "", "heuristic" },
    { "ieee8021x_wep", "", "heuristic" },
    { "ieee_80211h", "", "heuristic" },
    { "igmpEnabled", "0", "heuristic" },
    { "IgmpSnEnable", "1", "raw-kv-blob" },
    { "inet_addr", "", "heuristic" },
    { "inet_aton", "", "heuristic" },
    { "inet_ntoa", "", "heuristic" },
    { "internetmode", "0", "heuristic" },
    { "ip_address", "", "heuristic" },
    { "ip_control_init", "", "heuristic" },
    { "ip_ctl_auto", "0", "api-set-arg1" },
    { "ip_ctl_autochange", "actrlFlag", "api-set-arg1" },
    { "ip_ctl_carrules", "0", "api-set-arg1" },
    { "ip_ctl_downtotal", "", "heuristic" },
    { "ip_ctl_uptotal", "", "heuristic" },
    { "ip_port_filter_init", "", "heuristic" },
    { "ip_qos", "", "heuristic" },
    { "ipaddr", "192.168.10.200", "heuristic" },
    { "IPPortFilterEnable", "0", "heuristic" },
    { "IPPortFilterRules", "", "heuristic" },
    { "ipsec_passthrough", "", "heuristic" },
    { "ipsecPassThru", "", "heuristic" },
    { "IPSECRules", "", "heuristic" },
    { "isolated_ssid", "test", "heuristic" },
    { "ITxBfEn", "", "heuristic" },
    { "Key1Str", "actrlFlag", "api-set-arg0" },
    { "Key1Type", "", "heuristic" },
    { "Key2Str", "actrlFlag", "api-set-arg0" },
    { "Key2Type", "", "heuristic" },
    { "Key3Str", "actrlFlag", "api-set-arg0" },
    { "Key3Type", "", "heuristic" },
    { "Key4Str", "actrlFlag", "api-set-arg0" },
    { "Key4Type", "", "heuristic" },
    { "L2TP", "", "heuristic" },
    { "l2tp_authcontype", "", "heuristic" },
    { "l2tp_contype", "", "heuristic" },
    { "l2tp_df_route", "", "heuristic" },
    { "l2tp_gateway", "192.168.10.200", "heuristic" },
    { "l2tp_idle_time", "", "heuristic" },
    { "l2tp_ipaddr", "192.168.10.200", "heuristic" },
    { "l2tp_lns_ip", "192.168.10.200", "heuristic" },
    { "l2tp_lns_port", "", "heuristic" },
    { "l2tp_mode", "0", "heuristic" },
    { "l2tp_mtu", "1500", "heuristic" },
    { "l2tp_mtusize", "1500", "heuristic" },
    { "l2tp_name", "", "heuristic" },
    { "l2tp_NAPT", "", "heuristic" },
    { "l2tp_netmask", "255.255.255.0", "heuristic" },
    { "l2tp_passthrough", "", "heuristic" },
    { "l2tp_password", "admin", "forced-policy" },
    { "l2tp_psword", "", "heuristic" },
    { "l2tp_server", "", "heuristic" },
    { "l2tp_serverdns", "8.8.8.8", "heuristic" },
    { "l2tp_session", "", "heuristic" },
    { "l2tp_username", "admin", "forced-policy" },
    { "l2tp_usrname", "", "heuristic" },
    { "l2tpGateway", "192.168.10.200", "heuristic" },
    { "l2tpIdletime", "", "heuristic" },
    { "l2tpIp", "192.168.10.200", "heuristic" },
    { "l2tpMode", "0", "heuristic" },
    { "l2tpNetmask", "255.255.255.0", "heuristic" },
    { "l2tpOPMode", "0", "heuristic" },
    { "l2tpPass", "admin", "heuristic" },
    { "l2tpPassThru", "", "heuristic" },
    { "l2tpPT", "", "heuristic" },
    { "l2tpServer", "", "heuristic" },
    { "l2tpServerDNS", "8.8.8.8", "heuristic" },
    { "l2tpUseDNS", "8.8.8.8", "heuristic" },
    { "l2tpUser", "admin", "forced-policy" },
    { "lan.sh", "", "heuristic" },
    { "lan2_ipaddr", "192.168.10.200", "heuristic" },
    { "lan2_netmask", "255.255.255.0", "heuristic" },
    { "Lan2Enabled", "0", "heuristic" },
    { "lan2enabled", "0", "heuristic" },
    { "lan2Netmask", "255.255.255.0", "heuristic" },
    { "lan_assignment", "", "heuristic" },
    { "lan_ipaddr", "192.168.10.200", "forced-policy" },
    { "lan_netmask", "255.255.0.0", "api-set-arg1" },
    { "lan_othmask", "actrlFlag", "api-set-arg1" },
    { "lan_ping_en", "", "heuristic" },
    { "lanDhcpType", "", "heuristic" },
    { "lanGateway", "192.168.10.200", "heuristic" },
    { "Language", "en", "heuristic" },
    { "language", "\"JavaScript\">", "raw-kv-blob" },
    { "lanNetmask", "255.255.255.0", "heuristic" },
    { "lanping", "", "heuristic" },
    { "lanPriDns", "8.8.8.8", "heuristic" },
    { "lanSecDns", "8.8.8.8", "heuristic" },
    { "LanWebEn", "1", "api-set-arg1" },
    { "LanWebMac0", "00:11:22:33:44:55", "heuristic" },
    { "LanWebMac1", "00:11:22:33:44:55", "heuristic" },
    { "LanWebMac2", "00:11:22:33:44:55", "heuristic" },
    { "LanWebMac3", "00:11:22:33:44:55", "heuristic" },
    { "last_access_time", "", "heuristic" },
    { "linktype_pptp", "", "heuristic" },
    { "lltdEnabled", "0", "heuristic" },
    { "load_dictionary", "", "heuristic" },
    { "load_host", "", "heuristic" },
    { "localAcl_ping", "", "heuristic" },
    { "localAcl_web", "", "heuristic" },
    { "localIPMode", "=%s\\n", "string-kv" },
    { "Login", "admin", "forced-policy" },
    { "logout_flag", "actrlFlag", "api-set-arg1" },
    { "low_download_queue_ceil", "", "heuristic" },
    { "low_download_queue_rate", "", "heuristic" },
    { "low_upload_queue_ceil", "", "heuristic" },
    { "low_upload_queue_rate", "", "heuristic" },
    { "m2u_enable", "0", "heuristic" },
    { "M2UEnabled", "0", "heuristic" },
    { "mac", "00:11:22:33:44:55", "heuristic" },
    { "mac0", "00:11:22:33:44:55", "heuristic" },
    { "mac1", "00:11:22:33:44:55", "heuristic" },
    { "mac2", "00:11:22:33:44:55", "heuristic" },
    { "mac3", "00:11:22:33:44:55", "heuristic" },
    { "mac_address", "00:11:22:33:44:55", "heuristic" },
    { "mac_clone", "00:11:22:33:44:55", "heuristic" },
    { "mac_clone_value", "00:11:22:33:44:55", "heuristic" },
    { "mac_filter_onoff", "00:11:22:33:44:55", "heuristic" },
    { "Macbutton", "1", "api-set-arg1" },
    { "macCloneEnabled", "0", "api-set-arg1" },
    { "macCloneEnbl", "00:11:22:33:44:55", "heuristic" },
    { "macCloneMac", "2", "api-set-arg1" },
    { "macenhance", "00:11:22:33:44:55", "heuristic" },
    { "macipport_filter", "00:11:22:33:44:55", "heuristic" },
    { "malicious_filter", "", "heuristic" },
    { "malicious_input_filter", "", "heuristic" },
    { "management_init", "", "heuristic" },
    { "matchPort_e", "", "heuristic" },
    { "matchPort_s", "", "heuristic" },
    { "mbssidapisolated", "00:11:22:33:44:55", "heuristic" },
    { "Model", "0", "heuristic" },
    { "mssid_1", "test", "heuristic" },
    { "MT7620AP_unknown", "", "heuristic" },
    { "mtu_dhcp", "1500", "heuristic" },
    { "mtu_dhcpplus", "1500", "heuristic" },
    { "mtu_l2tp", "1500", "heuristic" },
    { "mtu_pppoe", "1500", "heuristic" },
    { "mtu_pptp", "1500", "heuristic" },
    { "mtu_static", "1500", "heuristic" },
    { "n_2040_coexit", "", "heuristic" },
    { "n_amsdu", "", "heuristic" },
    { "n_autoba", "", "heuristic" },
    { "n_badecline", "", "heuristic" },
    { "n_bandwidth", "", "heuristic" },
    { "n_disallow_tkip", "192.168.10.200", "heuristic" },
    { "n_extcha", "", "heuristic" },
    { "n_gi", "", "heuristic" },
    { "n_mcs", "", "heuristic" },
    { "n_mode", "0", "heuristic" },
    { "n_rdg", "", "heuristic" },
    { "n_stbc", "", "heuristic" },
    { "natEnabled", "1", "heuristic" },
    { "natEnbl", "", "heuristic" },
    { "netmask", "255.255.255.0", "heuristic" },
    { "netmask_aton", "255.255.255.0", "heuristic" },
    { "netsniper_enable", "0", "heuristic" },
    { "netsniperEnabled", "0", "heuristic" },
    { "newpass", "admin", "heuristic" },
    { "NoForwarding", "", "heuristic" },
    { "NoForwardingBTNBSSID", "00:11:22:33:44:55", "heuristic" },
    { "NTPEnable", "0", "heuristic" },
    { "NTPEnabled", "0", "heuristic" },
    { "NTPServerIP", "192.168.10.200", "heuristic" },
    { "NTPSync", "", "heuristic" },
    { "ntptimezone", "", "heuristic" },
    { "nvmacaddr", "00:11:22:33:44:55", "heuristic" },
    { "nvram_bufget", "", "heuristic" },
    { "nvram_bufset", "", "heuristic" },
    { "nvram_commit", "", "heuristic" },
    { "nvram_get", "", "heuristic" },
    { "nvram_init", "", "heuristic" },
    { "nvram_set", "", "heuristic" },
    { "old_firmware", "actrlFlag", "api-set-arg1" },
    { "on_off", "", "heuristic" },
    { "OperationMode", "1", "heuristic" },
    { "opMode", "0", "heuristic" },
    { "oProto", "", "heuristic" },
    { "own_ip_addr", "", "heuristic" },
    { "pass", "admin", "heuristic" },
    { "passphrase", "admin", "forced-policy" },
    { "Password", "admin", "forced-policy" },
    { "password", "admin", "forced-policy" },
    { "PASSWORD_MISMATCH", "admin", "forced-policy" },
    { "PATH_INFO", "", "heuristic" },
    { "PATH_TRANSLATED", "", "heuristic" },
    { "PBC_SESSION_OVERLAP", "", "heuristic" },
    { "ph1Mode", "=%s\\n", "string-kv" },
    { "pingFrmWANFilterEnabled", "0", "heuristic" },
    { "pkt_aggregate", "", "heuristic" },
    { "PktAggregate", "", "heuristic" },
    { "port_forward", "", "heuristic" },
    { "portal_manage_enable", "0", "api-set-arg1" },
    { "portalmange_enable", "0", "heuristic" },
    { "portFilterEnabled", "0", "heuristic" },
    { "PortForwardEnable", "0", "api-set-arg1" },
    { "portForwardEnabled", "0", "heuristic" },
    { "PortForwardRules", "", "heuristic" },
    { "PortTriggerEnable", "0", "heuristic" },
    { "PortTriggerRules", "", "heuristic" },
    { "ppp0", "", "heuristic" },
    { "pppIp", "192.168.10.200", "heuristic" },
    { "pppnetmask", "255.255.255.0", "heuristic" },
    { "PPPOE", "", "heuristic" },
    { "pppoe_contype", "", "heuristic" },
    { "pppoe_idletime", "", "heuristic" },
    { "pppoe_mtusize", "1500", "heuristic" },
    { "pppoe_psword", "", "heuristic" },
    { "pppoe_sername", "", "heuristic" },
    { "pppoe_usrname", "", "heuristic" },
    { "pppoeendtimehour", "", "heuristic" },
    { "pppoeendtimemin", "", "heuristic" },
    { "pppoeIdleTime", "", "heuristic" },
    { "pppoeOPMode", "0", "heuristic" },
    { "pppoePass", "admin", "heuristic" },
    { "pppoeREnabled", "0", "heuristic" },
    { "pppoeREnbl", "", "heuristic" },
    { "pppoeSrv_name", "", "heuristic" },
    { "pppoestarttimehour", "", "heuristic" },
    { "pppoestarttimemin", "", "heuristic" },
    { "pppoeUser", "admin", "forced-policy" },
    { "PPTP", "", "heuristic" },
    { "pptp_contype", "", "heuristic" },
    { "pptp_enable", "0", "heuristic" },
    { "pptp_gateway", "192.168.10.200", "heuristic" },
    { "pptp_gw", "192.168.10.200", "heuristic" },
    { "pptp_idletime", "", "heuristic" },
    { "pptp_ipaddr", "192.168.10.200", "heuristic" },
    { "pptp_mode", "0", "heuristic" },
    { "pptp_mtusize", "1500", "heuristic" },
    { "pptp_netmask", "255.255.255.0", "heuristic" },
    { "pptp_passthrough", "", "heuristic" },
    { "pptp_password", "admin", "forced-policy" },
    { "pptp_psword", "", "heuristic" },
    { "pptp_server", "", "heuristic" },
    { "pptp_serverdns", "8.8.8.8", "heuristic" },
    { "pptp_username", "admin", "forced-policy" },
    { "pptp_usrname", "", "heuristic" },
    { "pptpGateway", "192.168.10.200", "heuristic" },
    { "pptpIp", "192.168.10.200", "heuristic" },
    { "pptpMode", "0", "heuristic" },
    { "pptpNetmask", "255.255.255.0", "heuristic" },
    { "pptpPass", "admin", "heuristic" },
    { "pptpPassThru", "", "heuristic" },
    { "pptpPT", "", "heuristic" },
    { "pptpServer", "", "heuristic" },
    { "pptpServerDNS", "8.8.8.8", "heuristic" },
    { "pptpUseDNS", "8.8.8.8", "heuristic" },
    { "pptpUser", "admin", "forced-policy" },
    { "pre_shared_key", "", "heuristic" },
    { "PreAuth", "", "heuristic" },
    { "PreAuthifname", "", "heuristic" },
    { "product_do_security_setting", "", "heuristic" },
    { "product_do_wmm_setting", "", "heuristic" },
    { "product_modules", "", "heuristic" },
    { "prot0speed", "actrlFlag", "api-set-arg1" },
    { "prot1speed", "0", "api-set-arg1" },
    { "prot2speed", "0", "api-set-arg1" },
    { "prot3speed", "0", "api-set-arg1" },
    { "prot4speed", "1", "api-set-arg1" },
    { "proto", "", "heuristic" },
    { "protocol", "", "heuristic" },
    { "psk", "=%s\\n", "string-kv" },
    { "PSK", "admin", "heuristic" },
    { "pskValue", "admin", "heuristic" },
    { "pt_status", "", "heuristic" },
    { "QOS_PROFILE", "", "heuristic" },
    { "QoSAF1DLCeil", "", "heuristic" },
    { "QoSAF1DLRate", "", "heuristic" },
    { "QoSAF1ULCeil", "", "heuristic" },
    { "QoSAF1ULRate", "", "heuristic" },
    { "QoSAF2DLCeil", "", "heuristic" },
    { "QoSAF2DLRate", "", "heuristic" },
    { "QoSAF2ULCeil", "", "heuristic" },
    { "QoSAF2ULRate", "", "heuristic" },
    { "QoSAF5DLCeil", "", "heuristic" },
    { "QoSAF5DLRate", "", "heuristic" },
    { "QoSAF5ULCeil", "", "heuristic" },
    { "QoSAF5ULRate", "", "heuristic" },
    { "QoSAF6DLCeil", "", "heuristic" },
    { "QoSAF6DLRate", "", "heuristic" },
    { "QoSAF6ULCeil", "", "heuristic" },
    { "QoSAF6ULRate", "", "heuristic" },
    { "QoSDLRules", "", "heuristic" },
    { "QoSDownloadBandwidth", "", "heuristic" },
    { "QoSDownloadBandwidth_custom", "", "heuristic" },
    { "QoSEnable", "0", "heuristic" },
    { "QoSModel", "0", "heuristic" },
    { "QoSPortBasedRules", "", "heuristic" },
    { "QoSReserveBandwidth", "", "heuristic" },
    { "QoSSelect", "", "heuristic" },
    { "QoSULRules", "", "heuristic" },
    { "QoSUploadBandwidth", "", "heuristic" },
    { "QoSUploadBandwidth_custom", "", "heuristic" },
    { "QUERY_STRING", "", "heuristic" },
    { "quick_setup_mode", "actrlFlag", "api-set-arg1" },
    { "radiobutton", "", "heuristic" },
    { "radiohiddenButton", "", "heuristic" },
    { "RadioOff", "1", "api-set-arg1" },
    { "RadioOn", "0", "raw-kv-blob" },
    { "radiosrv", "", "heuristic" },
    { "RADIUS_Key", " ", "api-set-arg0" },
    { "RADIUS_Port", "1812", "api-set-arg1" },
    { "RADIUS_Server", "0", "api-set-arg1" },
    { "radvdEnabled", "0", "heuristic" },
    { "rai0", "", "heuristic" },
    { "rd_region", "", "heuristic" },
    { "RDRegion", "", "heuristic" },
    { "read_configed_rules_from_flash", "", "heuristic" },
    { "redirect_is_already_set", "", "heuristic" },
    { "relatePort_e", "", "heuristic" },
    { "relatePort_s", "", "heuristic" },
    { "release_dictionary", "", "heuristic" },
    { "remark_dscp", "", "heuristic" },
    { "REMOTE_ADDR", "", "heuristic" },
    { "REMOTE_HOST", "", "heuristic" },
    { "REMOTE_USER", "admin", "forced-policy" },
    { "remoteGWAddr", "=%s\\n", "string-kv" },
    { "remoteIP", "=%s\\n", "string-kv" },
    { "remoteIPMode", "=%s\\n", "string-kv" },
    { "RemoteManagement", "0", "api-set-arg1" },
    { "remoteManagementEnabled", "0", "heuristic" },
    { "remoteMask", "=%s\\n", "string-kv" },
    { "remotesyslog", "", "heuristic" },
    { "repeater_scan_flag", "", "heuristic" },
    { "repeater_scan_flag_5g", "", "heuristic" },
    { "Repeater_SYN_Channel", "", "heuristic" },
    { "RepeaterBSSID", "00:11:22:33:44:55", "heuristic" },
    { "RepeaterMode", "0", "heuristic" },
    { "RepeaterSSID", "test", "heuristic" },
    { "REQUEST_METHOD", "", "heuristic" },
    { "RIPEnable", "0", "heuristic" },
    { "RoutingRules", "", "heuristic" },
    { "rprise", "", "heuristic" },
    { "rt_enable_h", "0", "heuristic" },
    { "rt_ipaddr", "192.168.10.200", "heuristic" },
    { "rt_port", "", "heuristic" },
    { "RTDEVAP_unknown", "", "heuristic" },
    { "RTSThreshold", "", "heuristic" },
    { "RUPPPOE", "", "heuristic" },
    { "rutIPSec_calPrefixLen", "", "heuristic" },
    { "rx_stream", "", "heuristic" },
    { "s_filter_rules", "", "heuristic" },
    { "s_ip", "192.168.10.200", "heuristic" },
    { "s_mac", "00:11:22:33:44:55", "heuristic" },
    { "save_def_route", "", "heuristic" },
    { "SCRIPT_NAME", "", "heuristic" },
    { "search_desc", "", "heuristic" },
    { "security_enable", "0", "heuristic" },
    { "security_mode", "0", "heuristic" },
    { "security_shared_mode", "0", "heuristic" },
    { "SERVER_ADDR", "", "heuristic" },
    { "SERVER_HOST", "", "heuristic" },
    { "SERVER_NAME", "", "heuristic" },
    { "SERVER_PORT", "", "heuristic" },
    { "SERVER_PROTOCOL", "", "heuristic" },
    { "SERVER_SOFTWARE", "", "heuristic" },
    { "SERVER_URL", "", "heuristic" },
    { "session_timeout_interval", "0", "heuristic" },
    { "sethttp_sharefile", "", "heuristic" },
    { "setipsec_config", "", "heuristic" },
    { "short_preamble", "", "heuristic" },
    { "short_slot", "", "heuristic" },
    { "ShortSlot", "", "heuristic" },
    { "SinglePortForwardEnable", "1", "api-set-arg1" },
    { "singlePortForwardEnabled", "0", "heuristic" },
    { "SinglePortForwardRules", "", "heuristic" },
    { "sip_address", "", "heuristic" },
    { "sip_address2", "", "heuristic" },
    { "sip_alg", "", "heuristic" },
    { "SPIFWEnabled", "0", "api-set-arg1" },
    { "spiFWEnabled", "0", "heuristic" },
    { "srcnetmask", "255.255.255.0", "heuristic" },
    { "SSID", "actrlFlag", "api-set-arg0" },
    { "ssid", "test", "heuristic" },
    { "SSID1", "1", "api-set-arg1" },
    { "SSID2", "test", "heuristic" },
    { "SSID3", "test", "heuristic" },
    { "SSID4", "test", "heuristic" },
    { "ssidenable1", "1", "api-set-arg1" },
    { "ssidIndex", "test", "heuristic" },
    { "sta_acm_all", "", "heuristic" },
    { "sta_aifsn_all", "", "heuristic" },
    { "sta_cwmax_all", "", "heuristic" },
    { "sta_cwmin_all", "", "heuristic" },
    { "sta_dns_l2tp", "8.8.8.8", "heuristic" },
    { "sta_dns_pptp", "8.8.8.8", "heuristic" },
    { "sta_txop_all", "", "heuristic" },
    { "staip_gateway", "192.168.10.200", "heuristic" },
    { "staip_ipaddr", "192.168.10.200", "heuristic" },
    { "staip_mtusize", "1500", "heuristic" },
    { "staip_netmask", "255.255.255.0", "heuristic" },
    { "startScanUplinkAp", "actrlFlag", "api-set-arg1" },
    { "staticGateway", "192.168.10.200", "heuristic" },
    { "staticNetmask", "255.255.255.0", "heuristic" },
    { "staticPriDns", "8.8.8.8", "heuristic" },
    { "staticSecDns", "8.8.8.8", "heuristic" },
    { "statuscheckpppoeuser", "admin", "forced-policy" },
    { "stpEnabled", "0", "heuristic" },
    { "strip_path", "", "heuristic" },
    { "synflood_filter", "", "heuristic" },
    { "synflood_input_filter", "", "heuristic" },
    { "syslogIp", "192.168.10.200", "heuristic" },
    { "sz11bChannel", "", "heuristic" },
    { "tcp_flood_en", "", "heuristic" },
    { "tcp_flood_enable", "0", "heuristic" },
    { "tcp_flood_threshold", "", "heuristic" },
    { "tcp_timeout", "0", "heuristic" },
    { "TcpTimeout", "0", "heuristic" },
    { "telnetd", "", "heuristic" },
    { "telnetEnabled", "1", "heuristic" },
    { "time_zone", "", "heuristic" },
    { "tProto", "", "heuristic" },
    { "tx_burst", "", "heuristic" },
    { "tx_power", "", "heuristic" },
    { "tx_stream", "", "heuristic" },
    { "TxBurst", "1", "api-set-arg1" },
    { "TxPower", "", "heuristic" },
    { "TxPreamble", "", "heuristic" },
    { "TxRate", "", "heuristic" },
    { "TZ", "UCT_0", "heuristic" },
    { "udp_flood_en", "", "heuristic" },
    { "udp_flood_enable", "0", "heuristic" },
    { "udp_flood_threshold", "", "heuristic" },
    { "udp_timeout", "0", "heuristic" },
    { "UdpTimeout", "0", "heuristic" },
    { "UPLOAD_FILENAME", "", "heuristic" },
    { "upload_settings.cgi", "", "heuristic" },
    { "upload_torrent.cgi", "", "heuristic" },
    { "UploadBandwidth_Custom", "", "heuristic" },
    { "upnp_time_intervel", "", "heuristic" },
    { "upnp_ttl", "", "heuristic" },
    { "upnpEnabled", "0", "heuristic" },
    { "upnpEnbl", "", "heuristic" },
    { "upnpstat", "", "heuristic" },
    { "upnptimeInterval", "", "heuristic" },
    { "upnpTTL", "", "heuristic" },
    { "urlFilterEnable", "0", "heuristic" },
    { "user", "admin", "forced-policy" },
    { "UserCertFile", "", "heuristic" },
    { "username", "admin", "forced-policy" },
    { "VAP_unknown", "", "heuristic" },
    { "vht_bandwidth", "", "heuristic" },
    { "VHT_BW", "0", "api-set-arg1" },
    { "vht_bw", "", "heuristic" },
    { "VideoTurbine", "", "heuristic" },
    { "vpn-passthru.sh", "", "heuristic" },
    { "wan.sh", "wan_ipaddr", "api-set-arg0" },
    { "wan_dhcp_autodns", "1", "api-set-arg1" },
    { "wan_dhcp_flagMode", "actrlFlag", "api-set-arg1" },
    { "wan_dhcp_hn", "", "heuristic" },
    { "wan_dhcp_primary_dns", "0", "api-set-arg1" },
    { "wan_dhcp_secondary_dns", "actrlFlag", "api-set-arg1" },
    { "wan_dns1", "8.8.8.8", "heuristic" },
    { "wan_dns2", "8.8.8.8", "heuristic" },
    { "wan_gateway", "192.168.10.200", "heuristic" },
    { "wan_ipaddr", "actrlFlag", "api-set-arg1" },
    { "wan_l2tp_autodns", "1", "api-set-arg1" },
    { "wan_l2tp_automode", "actrlFlag", "api-set-arg1" },
    { "wan_l2tp_dfroute", "", "heuristic" },
    { "wan_l2tp_dns", "8.8.8.8", "heuristic" },
    { "wan_l2tp_gateway", "192.168.10.200", "heuristic" },
    { "wan_l2tp_ip", "0.0.0.0", "heuristic" },
    { "wan_l2tp_lns_port", "", "heuristic" },
    { "wan_l2tp_mode", "auto", "api-set-arg1" },
    { "wan_l2tp_nam", "", "heuristic" },
    { "wan_l2tp_napt", "", "heuristic" },
    { "wan_l2tp_netmask", "255.255.255.0", "heuristic" },
    { "wan_l2tp_opmode", "KeepAlive", "api-set-arg1" },
    { "wan_l2tp_optime", "", "heuristic" },
    { "wan_l2tp_pass", "admin", "heuristic" },
    { "wan_l2tp_primary_dns", "0", "api-set-arg1" },
    { "wan_l2tp_secondary_dns", "8.8.8.8", "heuristic" },
    { "wan_l2tp_server", "", "heuristic" },
    { "wan_l2tp_server_dns", "actrlFlag", "api-set-arg1" },
    { "wan_l2tp_session", "", "heuristic" },
    { "wan_l2tp_use_dns", "actrlFlag", "api-set-arg1" },
    { "wan_l2tp_user", "admin", "forced-policy" },
    { "WAN_MAC_ADDR", "00:11:22:33:44:55", "heuristic" },
    { "wan_mtu", "1500", "api-set-arg1" },
    { "wan_netmask", "255.255.255.0", "heuristic" },
    { "wan_netsniper_enable", "1", "api-set-arg1" },
    { "wan_para", "", "heuristic" },
    { "wan_parse", "", "heuristic" },
    { "wan_ping_en", "", "heuristic" },
    { "wan_pppoe_autodns", "0", "api-set-arg1" },
    { "wan_pppoe_endmin", "", "heuristic" },
    { "wan_pppoe_endthour", "", "heuristic" },
    { "wan_pppoe_ipaddrmode", "0.0.0.0", "heuristic" },
    { "wan_pppoe_opmode", "KeepAlive", "api-set-arg1" },
    { "wan_pppoe_optime", "60", "api-set-arg1" },
    { "wan_pppoe_pass", " ", "api-set-arg1" },
    { "wan_pppoe_primary_dns", "8.8.8.8", "heuristic" },
    { "wan_pppoe_secondary_dns", "8.8.8.8", "heuristic" },
    { "wan_pppoe_srvname", " ", "api-set-arg1" },
    { "wan_pppoe_starthour", "", "heuristic" },
    { "wan_pppoe_startmin", "", "heuristic" },
    { "wan_pppoe_staticIp", "0.0.0.0", "heuristic" },
    { "wan_pppoe_staticMask", "", "heuristic" },
    { "wan_pppoe_user", "admin", "forced-policy" },
    { "wan_pptp_autodns", "1", "api-set-arg1" },
    { "wan_pptp_automode", "actrlFlag", "api-set-arg1" },
    { "wan_pptp_defgw", "", "heuristic" },
    { "wan_pptp_dns", "8.8.8.8", "heuristic" },
    { "wan_pptp_gateway", "192.168.10.200", "heuristic" },
    { "wan_pptp_ip", "0.0.0.0", "heuristic" },
    { "wan_pptp_mode", "auto", "api-set-arg1" },
    { "wan_pptp_netmask", "255.255.255.0", "heuristic" },
    { "wan_pptp_opmode", "0", "heuristic" },
    { "wan_pptp_optime", "", "heuristic" },
    { "wan_pptp_pass", "admin", "heuristic" },
    { "wan_pptp_primary_dns", "0", "api-set-arg1" },
    { "wan_pptp_secondary_dns", "8.8.8.8", "heuristic" },
    { "wan_pptp_server", "", "heuristic" },
    { "wan_pptp_server_dns", "actrlFlag", "api-set-arg1" },
    { "wan_pptp_use_dns", "actrlFlag", "api-set-arg1" },
    { "wan_pptp_user", "admin", "forced-policy" },
    { "wan_primary_dns", "8.8.8.8", "heuristic" },
    { "wan_secondary_dns", "8.8.8.8", "heuristic" },
    { "wan_secondwan_ip", "0.0.0.0", "api-set-arg1" },
    { "wan_secondwan_netmask", "255.255.255.0", "heuristic" },
    { "wan_secondwan_type", "", "heuristic" },
    { "wan_session_ppp", "", "heuristic" },
    { "wan_set", "", "heuristic" },
    { "wan_speed", "0", "heuristic" },
    { "wanConnectionMode", "0", "api-set-arg1" },
    { "wanConnectionMode_MID", "DHCP", "heuristic" },
    { "wanping", "", "heuristic" },
    { "WANPingFilter", "0", "api-set-arg1" },
    { "wapi", "", "heuristic" },
    { "Wds0Key", "", "heuristic" },
    { "Wds1Key", "", "heuristic" },
    { "Wds2Key", "", "heuristic" },
    { "Wds3Key", "", "heuristic" },
    { "wds_encryp_key0", "", "heuristic" },
    { "wds_encryp_key1", "", "heuristic" },
    { "wds_encryp_key2", "", "heuristic" },
    { "wds_encryp_key3", "", "heuristic" },
    { "wds_encryp_type", "", "heuristic" },
    { "wds_list", "", "heuristic" },
    { "wds_mode", "0", "heuristic" },
    { "wds_phy_mode", "0", "heuristic" },
    { "WdsEnable", "0", "heuristic" },
    { "WdsEncrypType", "", "heuristic" },
    { "WdsList", "", "heuristic" },
    { "WdsPhyMode", "0", "heuristic" },
    { "web_filter", "", "heuristic" },
    { "websFilterActivex", "1", "api-set-arg1" },
    { "websFilterCookies", "1", "api-set-arg1" },
    { "websFilterJava", "1", "api-set-arg1" },
    { "websFilterProxy", "1", "api-set-arg1" },
    { "websHostFilters", "", "heuristic" },
    { "websURLFilters", "", "heuristic" },
    { "week_select_", "", "heuristic" },
    { "week_select_all", "", "heuristic" },
    { "WEP", "", "heuristic" },
    { "WEPAUTO", "", "heuristic" },
    { "wifi_unload.sh", "", "heuristic" },
    { "WifiSecurity", "", "heuristic" },
    { "wireless_bandmode", "1", "api-set-arg1" },
    { "wireless_para", "", "heuristic" },
    { "wireless_parse", "", "heuristic" },
    { "wireless_set", "", "heuristic" },
    { "wireless_states", "", "heuristic" },
    { "wirelessApcli_5g", "", "heuristic" },
    { "WirelessMode", "actrlFlag", "api-set-arg1" },
    { "Wirelessmode", "0", "heuristic" },
    { "wirelessmode", "0", "heuristic" },
    { "wizaecheck", "1", "api-set-arg1" },
    { "wizard_APSecurity", "", "heuristic" },
    { "wizard_clichosemode", "0", "heuristic" },
    { "wizard_commitSetWan", "", "heuristic" },
    { "wizard_confWPAGeneral", "", "heuristic" },
    { "wizard_end", "", "heuristic" },
    { "wizard_head", "", "heuristic" },
    { "wizard_setWan", "", "heuristic" },
    { "wizard_wantype", "", "heuristic" },
    { "wizard_wireless_5G", "", "heuristic" },
    { "wizard_wireless_setup", "", "heuristic" },
    { "wizard_wirelessGetSecurity", "", "heuristic" },
    { "wizardstep1_back", "", "heuristic" },
    { "wizardstep1_next", "", "heuristic" },
    { "wizardstep1_next_ignore_wan_setting", "", "heuristic" },
    { "wizardstep2_back", "", "heuristic" },
    { "wizardstep2_next", "", "heuristic" },
    { "wizardstep2_wantype", "", "heuristic" },
    { "wizardstep3pppoe_back", "", "heuristic" },
    { "wizardstep3pppoe_next", "", "heuristic" },
    { "wizardstep3static_back", "", "heuristic" },
    { "wizardstep3static_next", "", "heuristic" },
    { "wizardstep4_back", "", "heuristic" },
    { "wizardstep4_back_ignore_wan_setting", "", "heuristic" },
    { "wizardstep4_band", "", "heuristic" },
    { "wizardstep4_chanwid", "", "heuristic" },
    { "wizardstep4_next", "", "heuristic" },
    { "wizardstep4_pskpwd", "admin", "forced-policy" },
    { "wizardstep4_pskpwd_2", "admin", "forced-policy" },
    { "wizardstep4_pskpwd_5", "admin", "forced-policy" },
    { "wizardstep4_sec", "", "heuristic" },
    { "wizardstep4_ssid", "test", "heuristic" },
    { "wizardstep4_ssid_2", "test", "heuristic" },
    { "wizardstep4_ssid_5", "test", "heuristic" },
    { "wizardstep4_wlanDisabled", "", "heuristic" },
    { "wizardstep54_back", "", "heuristic" },
    { "wizardstep54_band", "", "heuristic" },
    { "wizardstep54_chanwid", "", "heuristic" },
    { "wizardstep54_next", "", "heuristic" },
    { "wizardstep54_pskpwd", "admin", "forced-policy" },
    { "wizardstep54_sec", "", "heuristic" },
    { "wizardstep54_ssid", "test", "heuristic" },
    { "wizardstep54_wlanDisabled", "", "heuristic" },
    { "wizardstep5_back", "", "heuristic" },
    { "wizardstep5_next", "", "heuristic" },
    { "wlanAcEnabled", "0", "heuristic" },
    { "wlanDisabled", "", "heuristic" },
    { "wmm_capable", "", "heuristic" },
    { "wmm_enable", "0", "heuristic" },
    { "WmmCapable", "33", "api-set-arg1" },
    { "WPA", "", "heuristic" },
    { "WPA-Enterprise", "", "heuristic" },
    { "WPA-PSK", "admin", "heuristic" },
    { "WPA1WPA2", "", "heuristic" },
    { "WPA2", "", "heuristic" },
    { "WPA2-Enterprise", "", "heuristic" },
    { "WPA2-PSK", "admin", "heuristic" },
    { "WPA2PSK", "admin", "heuristic" },
    { "WPAPSK", "actrlFlag", "api-set-arg0" },
    { "WPAPSK1", "TKIPAES", "api-set-arg1" },
    { "WPAPSKWPA2PSK", "admin", "heuristic" },
    { "WPSEnable", "0", "heuristic" },
    { "WpsMode2", "1", "api-set-arg1" },
    { "WpsMode5", "0", "api-set-arg1" },
    { "WpsPin", "", "heuristic" },
    { "write_index_rule_to_flash", "", "heuristic" },
    { "write_queue_head_to_flash", "", "heuristic" },
    { "WSC_EAP_RSP_DONE_SENT", "", "heuristic" },
    { "WSC_ERROR_DEV_PWD_AUTH_FAIL", "admin", "forced-policy" },
    { "WSC_ERROR_HASH_FAIL", "", "heuristic" },
    { "WSC_ERROR_HMAC_FAIL", "00:11:22:33:44:55", "heuristic" },
    { "WSC_START_ASSOC", "", "heuristic" },
    { "WscConfigured", "0x680", "api-set-arg1" },
    { "WscConfMethods", "0x680", "api-set-arg1" },
    { "WscConfMode", "%d", "raw-kv-blob" },
    { "WscMode", "2", "raw-kv-blob" },
    { "WscModeOption", "1", "api-set-arg1" },
    { "WscSSID", "test", "heuristic" },
    { "WscVendorPinCode", "", "heuristic" },
    { NULL, NULL, NULL }
};

typedef struct dyn_kv {
    char *key;
    char *value;
    struct dyn_kv *next;
} dyn_kv_t;

static dyn_kv_t *dyn_head = NULL;

static int looks_like_index_arg(const void *p)
{
    uintptr_t x = (uintptr_t)p;
    return x < 4096U;
}

static char *xstrdup0(const char *s)
{
    if (!s) s = "";
    char *p = strdup(s);
    if (!p) {
        fprintf(stderr, "[nvram_fake] strdup failed\n");
        abort();
    }
    return p;
}

static void trim_inplace(char *s)
{
    char *p;
    if (!s) return;
    while (*s && isspace((unsigned char)*s)) {
        memmove(s, s + 1, strlen(s));
    }
    p = s + strlen(s);
    while (p > s && isspace((unsigned char)p[-1])) {
        *--p = 0;
    }
}

static const char *lookup_static(const char *key)
{
    int i;
    if (!key) return NULL;
    for (i = 0; static_kv[i].key; i++) {
        if (strcmp(static_kv[i].key, key) == 0) {
            return static_kv[i].value ? static_kv[i].value : "";
        }
    }
    return NULL;
}

static const char *lookup_dyn(const char *key)
{
    dyn_kv_t *p;
    if (!key) return NULL;
    for (p = dyn_head; p; p = p->next) {
        if (strcmp(p->key, key) == 0) {
            return p->value ? p->value : "";
        }
    }
    return NULL;
}

static const char *lookup_nvram_value(const char *key)
{
    const char *v;
    if (!key) return NULL;
    v = lookup_dyn(key);
    if (v) return v;
    v = lookup_static(key);
    if (v) return v;
    return "";
}

static void set_dyn(const char *key, const char *value)
{
    dyn_kv_t *p;
    if (!key || !*key) return;
    if (!value) value = "";
    for (p = dyn_head; p; p = p->next) {
        if (strcmp(p->key, key) == 0) {
            free(p->value);
            p->value = xstrdup0(value);
            return;
        }
    }
    p = (dyn_kv_t *)calloc(1, sizeof(*p));
    if (!p) return;
    p->key = xstrdup0(key);
    p->value = xstrdup0(value);
    p->next = dyn_head;
    dyn_head = p;
}

static void load_ini_file(const char *path)
{
    FILE *fp;
    char line[2048];
    if (!path || !*path) return;
    fp = fopen(path, "r");
    if (!fp) return;
    while (fgets(line, sizeof(line), fp)) {
        char *eq;
        trim_inplace(line);
        if (!line[0] || line[0] == '#' || line[0] == ';' || line[0] == '[') continue;
        eq = strchr(line, '=');
        if (!eq) continue;
        *eq++ = 0;
        trim_inplace(line);
        trim_inplace(eq);
        if (line[0]) set_dyn(line, eq);
    }
    fclose(fp);
}

__attribute__((constructor))
static void nvram_fake_ctor(void)
{
    const char *ini = getenv("NVRAM_FAKE_INI");
    if (ini && *ini) load_ini_file(ini);
    load_ini_file("./nvram.ini");
    fprintf(stderr, "[nvram_fake] loaded; override with NVRAM_FAKE_INI=/path/nvram.ini\n");
}

static const char *extract_get_key(void *arg0, va_list *ap)
{
    /*
     * Ralink/D-Link style often calls nvram_get(0, "key"), so arg0 == NULL
     * is a valid index argument and must still consume the next vararg.
     */
    if (looks_like_index_arg(arg0)) {
        return va_arg(*ap, const char *);
    }
    return (const char *)arg0;
}

static void extract_set_args(void *arg0, va_list *ap, const char **key, const char **value)
{
    *key = NULL;
    *value = NULL;
    /* arg0 == 0 may be a valid index: nvram_set(0, key, value). */
    if (looks_like_index_arg(arg0)) {
        *key = va_arg(*ap, const char *);
        *value = va_arg(*ap, const char *);
    } else {
        *key = (const char *)arg0;
        *value = va_arg(*ap, const char *);
    }
}

#define DEFINE_NVRAM_GETTER(fn, null_on_missing)                 \
char *fn(void *arg0, ...)                                        \
{                                                                \
    va_list ap;                                                  \
    const char *key;                                             \
    const char *value;                                           \
    va_start(ap, arg0);                                          \
    key = extract_get_key(arg0, &ap);                             \
    va_end(ap);                                                  \
    value = lookup_nvram_value(key);                              \
    fprintf(stderr, "[nvram_fake] %s(%s) -> %s\n", #fn,           \
            key ? key : "(null)", value ? value : "(null)");    \
    if (!value && (null_on_missing)) return NULL;                 \
    return xstrdup0(value ? value : "");                         \
}

DEFINE_NVRAM_GETTER(nvram_get, 1)
DEFINE_NVRAM_GETTER(nvram_bufget, 1)
DEFINE_NVRAM_GETTER(nvram_safe_get, 0)
DEFINE_NVRAM_GETTER(bcm_nvram_get, 1)
DEFINE_NVRAM_GETTER(wlcsm_nvram_get, 1)
DEFINE_NVRAM_GETTER(dni_nvram_get, 1)
DEFINE_NVRAM_GETTER(envram_get, 1)
DEFINE_NVRAM_GETTER(acosNvramConfig_get, 1)
DEFINE_NVRAM_GETTER(uci_get, 1)
DEFINE_NVRAM_GETTER(cfg_get, 1)
DEFINE_NVRAM_GETTER(config_get, 1)
DEFINE_NVRAM_GETTER(xmldbc_get, 1)

#define DEFINE_NVRAM_SETTER(fn)                                  \
int fn(void *arg0, ...)                                           \
{                                                                \
    va_list ap;                                                  \
    const char *key, *value;                                     \
    va_start(ap, arg0);                                          \
    extract_set_args(arg0, &ap, &key, &value);                    \
    va_end(ap);                                                  \
    fprintf(stderr, "[nvram_fake] %s(%s,%s)\n", #fn,              \
            key ? key : "(null)", value ? value : "(null)");    \
    if (key) set_dyn(key, value ? value : "");                   \
    return 0;                                                    \
}

DEFINE_NVRAM_SETTER(nvram_set)
DEFINE_NVRAM_SETTER(nvram_bufset)
DEFINE_NVRAM_SETTER(bcm_nvram_set)
DEFINE_NVRAM_SETTER(dni_nvram_set)
DEFINE_NVRAM_SETTER(envram_set)
DEFINE_NVRAM_SETTER(acosNvramConfig_set)
DEFINE_NVRAM_SETTER(uci_set)
DEFINE_NVRAM_SETTER(cfg_set)
DEFINE_NVRAM_SETTER(config_set)
DEFINE_NVRAM_SETTER(xmldbc_set)

int nvram_unset(void *arg0, ...)
{
    va_list ap;
    const char *key;
    va_start(ap, arg0);
    key = extract_get_key(arg0, &ap);
    va_end(ap);
    fprintf(stderr, "[nvram_fake] nvram_unset(%s)\n", key ? key : "(null)");
    if (key) set_dyn(key, "");
    return 0;
}

int nvram_getall(void *arg0, ...)
{
    va_list ap;
    char *buf = NULL;
    int count = NVRAM_FAKE_GETALL_MAX;
    char *p;
    int left;
    int i;
    dyn_kv_t *d;

    va_start(ap, arg0);
    if (looks_like_index_arg(arg0)) {
        buf = va_arg(ap, char *);
        /* Ralink-style nvram_getall(index, buf) often has no length arg. */
        count = NVRAM_FAKE_GETALL_MAX;
    } else {
        buf = (char *)arg0;
        count = va_arg(ap, int);
        if (count <= 0 || count > NVRAM_FAKE_GETALL_MAX) count = NVRAM_FAKE_GETALL_MAX;
    }
    va_end(ap);
    if (!buf || count <= 2) return -1;

    p = buf;
    left = count;
#define APPEND_KV(k, v) do {                                      \
        int n;                                                     \
        if (!(k)) break;                                           \
        n = snprintf(p, left, "%s=%s", (k), (v) ? (v) : "");      \
        if (n < 0 || n + 2 >= left) goto done;                     \
        p += n + 1;                                                \
        left -= n + 1;                                             \
    } while (0)

    for (i = 0; static_kv[i].key; i++) APPEND_KV(static_kv[i].key, lookup_nvram_value(static_kv[i].key));
    for (d = dyn_head; d; d = d->next) APPEND_KV(d->key, d->value);
done:
    if (left > 0) *p++ = '\0';
    fprintf(stderr, "[nvram_fake] nvram_getall -> %ld bytes\n", (long)(p - buf));
    return 0;
}

int nvram_match(void *arg0, ...)
{
    va_list ap;
    const char *key, *expect, *got;
    va_start(ap, arg0);
    if (looks_like_index_arg(arg0)) {
        key = va_arg(ap, const char *);
        expect = va_arg(ap, const char *);
    } else {
        key = (const char *)arg0;
        expect = va_arg(ap, const char *);
    }
    va_end(ap);
    got = lookup_nvram_value(key);
    return (got && expect && strcmp(got, expect) == 0) ? 1 : 0;
}

int nvram_invmatch(void *arg0, ...)
{
    va_list ap;
    const char *key, *expect, *got;
    va_start(ap, arg0);
    if (looks_like_index_arg(arg0)) {
        key = va_arg(ap, const char *);
        expect = va_arg(ap, const char *);
    } else {
        key = (const char *)arg0;
        expect = va_arg(ap, const char *);
    }
    va_end(ap);
    got = lookup_nvram_value(key);
    return (got && expect && strcmp(got, expect) == 0) ? 0 : 1;
}

int acosNvramConfig_match(void *arg0, ...)
{
    va_list ap;
    const char *key, *expect, *got;
    va_start(ap, arg0);
    key = (const char *)arg0;
    expect = va_arg(ap, const char *);
    va_end(ap);
    got = lookup_nvram_value(key);
    return (got && expect && strcmp(got, expect) == 0) ? 1 : 0;
}

int acosNvramConfig_invmatch(void *arg0, ...)
{
    va_list ap;
    const char *key, *expect, *got;
    va_start(ap, arg0);
    key = (const char *)arg0;
    expect = va_arg(ap, const char *);
    va_end(ap);
    got = lookup_nvram_value(key);
    return (got && expect && strcmp(got, expect) == 0) ? 0 : 1;
}

int nvram_commit()
{
    fprintf(stderr, "[nvram_fake] nvram_commit()\n");
    return 0;
}

int nvram_init()
{
    fprintf(stderr, "[nvram_fake] nvram_init()\n");
    return 0;
}

int tcapi_get(const char *node, const char *key, char *buf)
{
    const char *v = lookup_nvram_value(key ? key : node);
    fprintf(stderr, "[nvram_fake] tcapi_get(%s,%s) -> %s\n",
            node ? node : "(null)", key ? key : "(null)", v ? v : "");
    if (buf) strcpy(buf, v ? v : "");
    return 0;
}

int tcapi_set(const char *node, const char *key, const char *value)
{
    fprintf(stderr, "[nvram_fake] tcapi_set(%s,%s,%s)\n",
            node ? node : "(null)", key ? key : "(null)", value ? value : "(null)");
    if (key) set_dyn(key, value ? value : "");
    return 0;
}

int tcapi_commit()
{
    fprintf(stderr, "[nvram_fake] tcapi_commit()\n");
    return 0;
}
